In [31]:
import pandas as pd

df_train = pd.read_csv('data/train.csv', encoding="ISO-8859-1")
df_test = pd.read_csv('data/test.csv', encoding="ISO-8859-1")

dfs = (df_train, df_test)

for df in dfs:
    df['question1'] = df['question1'].str.lower()
    df['question2'] = df['question2'].str.lower()
    
    q_kcores = pd.read_csv('data/question_kcores.csv', encoding="ISO-8859-1")
    
    q_kcores['question1'] = q_kcores['question']
    del q_kcores['question']
    df['q1_kcores'] = df.merge(q_kcores, 'left')['kcores']
    
    q_kcores['question2'] = q_kcores['question1']
    del q_kcores['question1']
    df['q2_kcores'] = df.merge(q_kcores, 'left')['kcores']
    
    df['q1_q2_kcores_ratio'] = (df['q1_kcores'] / df['q2_kcores']).apply(lambda x: x if x < 1. else 1./x)
    df['q1_q2_kcores_diff'] = (df['q1_kcores'] - df['q2_kcores']).apply(abs)
    df['q1_q2_kcores_diff_normed'] = (df['q1_kcores'] - df['q2_kcores']).apply(abs) / (df['q1_kcores'] + df['q2_kcores'])

In [35]:
df_train, df_test = dfs
df_train = df_train[['q1_kcores', 'q2_kcores', 'q1_q2_kcores_ratio', 'q1_q2_kcores_diff', 'q1_q2_kcores_diff_normed']]
df_test = df_test[['q1_kcores', 'q2_kcores', 'q1_q2_kcores_ratio', 'q1_q2_kcores_diff', 'q1_q2_kcores_diff_normed']]
df_train.head(20)

,q1_kcores,q2_kcores,q1_q2_kcores_ratio,q1_q2_kcores_diff,q1_q2_kcores_diff_normed
0,1.0,1.0,1.000000,0.0,0.0
1,1.0,1.0,1.000000,0.0,0.0
2,1.0,1.0,1.000000,0.0,0.0
3,1.0,1.0,1.000000,0.0,0.0
4,1.0,1.0,1.000000,0.0,0.0
5,1.0,1.0,1.000000,0.0,0.0
6,1.0,1.0,1.000000,0.0,0.0
7,1.0,1.0,1.000000,0.0,0.0
8,2.0,2.0,1.000000,0.0,0.0
9,1.0,1.0,1.000000,0.0,0.0
10,1.0,1.0,1.000000,0.0,0.0
11,1.0,1.0,1.000000,0.0,0.0
12,2.0,2.0,1.000000,0.0,0.0
13,2.0,2.0,1.000000,0.0,0.0
14,2.0,2.0,1.000000,0.0,0.0
15,7.0,7.0,1.000000,0.0,0.0
16,1.0,1.0,1.000000,0.0,0.0
17,1.0,1.0,1.000000,0.0,0.0
18,20.0,30.0,0.666667,10.0,0.2
19,1.0,1.0,1.000000,0.0,0.0

In [36]:
df_train.to_csv("data/kcores_train.csv", index=False)
df_test.to_csv("data/kcores_test.csv", index=False)